2025-04-28 11:47:54,002 :: WARNING :: http://127.0.0.1:8080/api not found
2025-04-28 11:49:39,432 :: WARNING :: http://127.0.0.1:8080/docs not found
2025-04-28 11:49:46,616 :: WARNING :: http://127.0.0.1:8080/api/docs not found
2025-04-28 11:49:56,550 :: WARNING :: http://127.0.0.1:8080/docs not found
2025-04-28 11:53:00,116 :: WARNING :: http://127.0.0.1:8080/api not found
2025-04-28 11:53:22,376 :: WARNING :: http://127.0.0.1:8080/api/docs not found
2025-04-28 11:59:25,021 :: WARNING :: http://127.0.0.1:8080/api/docs not found
2025-04-28 12:01:57,008 :: WARNING :: http://127.0.0.1:8080/v1/scan not found
2025-04-28 12:02:10,863 :: WARNING :: http://127.0.0.1:8080/scan not found
2025-04-28 12:02:37,667 :: WARNING :: http://127.0.0.1:8080/v1/scan not found
2025-04-28 12:02:37,702 :: WARNING :: http://127.0.0.1:8080/scan not found
2025-04-28 12:03:06,954 :: WARNING :: http://127.0.0.1:8080/scan not found
2025-04-28 12:03:06,990 :: WARNING :: http://127.0.0.1:8080/v1/scan not found
2025-04-28 12:03:24,865 :: WARNING :: http://127.0.0.1:8080/scan not found
2025-04-28 12:03:24,914 :: WARNING :: http://127.0.0.1:8080/v1/scan not found
2025-04-28 12:05:23,111 :: WARNING :: http://127.0.0.1:8080/v1/scan not found
2025-04-28 12:05:23,145 :: WARNING :: http://127.0.0.1:8080/scan not found
2025-04-28 12:06:16,472 :: WARNING :: http://127.0.0.1:8080/api/v1/scan not found
2025-04-28 12:06:23,259 :: WARNING :: http://127.0.0.1:8080/api/docs not found
2025-04-28 12:10:02,494 :: WARNING :: http://127.0.0.1:8080/api/docs not found
2025-04-28 12:10:02,533 :: WARNING :: http://127.0.0.1:8080/v1/scan not found
2025-04-28 12:10:16,501 :: WARNING :: http://127.0.0.1:8080/docs not found
2025-04-28 12:10:33,758 :: WARNING :: http://127.0.0.1:8080/api/v1/docs not found
2025-04-28 12:11:42,312 :: WARNING :: http://127.0.0.1:8080/v1/scan not found
2025-04-28 12:11:42,354 :: WARNING :: http://127.0.0.1:8080/api/v1/docs not found
2025-04-28 12:11:53,967 :: WARNING :: http://127.0.0.1:8080/docs not found
2025-04-28 12:14:29,452 :: WARNING :: http://127.0.0.1:8080/docs not found
2025-04-28 12:14:29,484 :: WARNING :: http://127.0.0.1:8080/v1/scan not found
2025-04-28 12:14:48,311 :: WARNING :: http://127.0.0.1:8080/v1/scan not found
2025-04-28 12:14:49,709 :: WARNING :: http://127.0.0.1:8080/docs not found
2025-04-28 12:15:07,549 :: WARNING :: http://127.0.0.1:8080/docs not found
2025-04-28 12:17:21,340 :: WARNING :: http://127.0.0.1:8080/v1/scan not found
2025-04-28 12:40:26,155 :: ERROR :: 'dict' object is not callable
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\base.py", line 177, in __call__
  |     async with anyio.create_task_group() as task_group:
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 772, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    |     with recv_stream, send_stream, collapse_excgroups():
    |                                    ^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\nicegui\middlewares.py", line 10, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    |     raise app_exc
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\gzip.py", line 29, in __call__
    |     await responder(scope, receive, send)
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\gzip.py", line 126, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\gzip.py", line 46, in __call__
    |     await self.app(scope, receive, self.send_with_compression)
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    |     await route.handle(scope, receive, send)
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    |     content = await serialize_response(
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\fastapi\routing.py", line 201, in serialize_response
    |     return jsonable_encoder(response_content)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\fastapi\encoders.py", line 301, in jsonable_encoder
    |     for item in obj:
    |                 ^^^
    |   File "C:\Users\david\Documents\devs\SoniqueBay-app\backend\music_scan.py", line 18, in scan_music_files
    |     track = Track(
    |             ^^^^^^
    | TypeError: 'dict' object is not callable
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
                                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    raise exc
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\nicegui\middlewares.py", line 10, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\gzip.py", line 29, in __call__
    await responder(scope, receive, send)
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\gzip.py", line 126, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\gzip.py", line 46, in __call__
    await self.app(scope, receive, self.send_with_compression)
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\fastapi\routing.py", line 201, in serialize_response
    return jsonable_encoder(response_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\Documents\devs\SoniqueBay-app\.venv\Lib\site-packages\fastapi\encoders.py", line 301, in jsonable_encoder
    for item in obj:
                ^^^
  File "C:\Users\david\Documents\devs\SoniqueBay-app\backend\music_scan.py", line 18, in scan_music_files
    track = Track(
            ^^^^^^
TypeError: 'dict' object is not callable
